In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("demografia.csv",na_values = '.')

In [4]:
df = df.set_index("KRAJE") #zad1
df

,1965,1970,1980,1990,1995,2000,2005,2010a,2015,2020,2022
KRAJE,,,,,,,,,,,
Armenia,3.15,2.22,1.45,1.68,0.34,-0.03,0.11,0.41,-0.40,0.12,NaN
Austria,0.63,0.32,0.10,0.86,0.12,0.23,0.65,0.35,1.34,0.36,1.40
Azerbejdżan,2.85,2.12,1.50,1.21,1.08,0.81,1.07,1.26,1.17,0.52,-0.29
Belgia,0.75,-0.10,0.08,0.39,0.12,0.24,0.63,0.10,0.65,0.28,1.17
Białoruś,1.14,0.94,0.74,0.01,-0.33,-0.29,-0.51,0.01,0.18,NaN,NaN
Bułgaria,0.65,0.60,0.34,-1.12,-0.51,-0.51,-0.55,-0.78,-0.67,-0.50,-5.72
Chorwacja,0.69,0.40,0.06,-0.04,-0.02,0.37,-0.02,-0.31,-0.82,-0.54,-0.30
Cypr,0.81,0.80,1.14,1.76,1.35,0.87,2.30,0.16,0.15,0.90,1.77
Czechy,0.47,0.21,0.20,0.02,-0.11,-0.45,0.30,0.25,0.15,-1.86,2.96
Dania,0.81,0.69,0.03,0.21,0.67,0.36,0.30,0.47,0.84,0.30,1.01
Estonia,0.97,1.24,0.68,-0.18,-1.59,-0.37,-0.21,0.00,0.08,0.08,2.56
Finlandia,0.27,-0.35,0.34,0.48,0.35,0.19,0.36,0.44,0.28,0.15,0.28
Francja,0.72,0.96,0.55,0.56,0.41,0.59,0.72,0.55,0.27,0.25,0.29
Grecja,0.52,0.28,1.15,0.71,0.74,0.25,0.38,0.18,-0.69,-0.34,-0.63
Gruzja,1.23,1.15,0.83,0.53,-2.53,-0.77,1.85,0.74,-0.24,0.32,1.29
Hiszpania,1.04,1.56,1.05,0.12,0.20,1.03,1.67,0.36,-0.02,0.14,1.32
Holandia,1.34,1.24,0.83,0.79,0.45,0.77,0.18,0.49,0.46,0.39,1.25
Irlandia,0.31,0.94,1.17,0.40,0.62,1.45,2.35,0.29,1.03,0.86,2.65
Islandia,1.73,0.49,1.07,0.93,0.35,1.48,2.15,0.26,1.04,1.28,3.06
Litwa,1.20,1.32,0.53,0.22,-0.77,-0.72,-0.64,-2.57,-1.13,0.06,1.83
Luksemburg,0.90,0.40,0.38,1.34,1.51,0.88,1.70,1.93,2.33,1.38,2.39
Łotwa,0.96,0.62,0.23,-0.37,-1.25,-0.74,-0.51,-0.84,-0.87,-0.76,0.39
Malta,NaN,0.10,0.98,1.03,0.52,0.68,0.58,0.78,2.41,0.30,4.05
Niemcy,0.98,-0.26,0.28,0.81,0.34,0.12,-0.08,-0.06,1.20,-0.01,1.35
Norwegia,0.78,0.65,0.33,0.39,0.49,0.56,0.73,1.27,0.85,0.44,1.17
Polska,0.67,-0.04,0.90,0.38,0.07,-0.02,-0.04,0.09,-0.10,-0.31,-2.39
Portugalia,-0.67,-0.40,1.08,-0.43,0.26,0.60,0.38,-0.01,-0.32,0.02,1.11
Rosja,0.69,0.48,0.51,0.34,-0.22,-0.51,-0.50,0.66,NaN,NaN,NaN
Rumunia,0.54,1.09,0.67,-0.08,-0.25,-0.11,-0.22,-0.23,-0.56,-0.66,0.05
San Marino,1.14,2.29,7.23,0.87,1.41,1.17,1.10,NaN,0.66,NaN,0.34
Słowacja,0.95,0.75,0.83,0.43,0.22,0.07,0.08,0.19,0.09,0.03,-0.11
Słowenia,1.33,0.69,0.87,0.18,0.04,0.12,0.29,0.16,0.06,0.63,0.46
Szwajcaria,0.93,0.39,0.50,1.14,0.62,0.55,0.59,1.03,1.08,0.75,0.85
Szwecja,1.00,0.96,0.18,0.74,0.24,0.24,0.40,0.80,1.06,0.50,0.66
Ukraina,0.92,0.82,0.36,0.20,-0.84,-1.03,-0.75,-0.40,-0.40,-0.75,NaN
Węgry,0.25,0.29,-0.04,-0.02,-0.15,-0.21,-0.21,-0.29,-0.25,-0.40,-0.95
Wielka Brytania,0.60,0.42,0.10,0.32,0.26,0.36,0.62,0.66,0.81,NaN,NaN
Włochy,0.79,0.51,0.16,0.09,0.00,0.07,0.49,0.74,-0.21,-0.68,-0.30

In [5]:
df[df["2022"]==df["2022"].max()][["2022"]] #zad2

           2022
KRAJE
Malta      4.05

In [6]:
df[df == df.max()].dropna(how="all").stack() #zad 3

KRAJE
Armenia         1965     3.15
Cypr            1990     1.76
Irlandia        2005     2.35
Islandia        2000     1.48
Luksemburg      1995     1.51
                2010a    1.93
                2020     1.38
Malta           2015     2.41
                2022     4.05
San Marino      1970     2.29
                1980     7.23
dtype: float64

In [7]:
d2={"ID":[1, 2, 3, 4, 5],
    "Name":[ "Anna", "Jan", "Katarzyna", "Tomasz", "Michał"],
    "2nd Name":["Kowalska", "Nowak", "Wiśniewska", "Kaczmarek", "Zieliński"],
    "Job":["Manager", "Programista", "Konsultant", "Programista", "Manager"],
    "Age":[ 35, 28, 40, 30, 45],
    "Celery":[8000, 4500, 6000, 5500, 7000],
   }

In [8]:
df2 = pd.DataFrame(d2)

In [9]:
df2 = df2.set_index("ID")

In [10]:
df2

         Name    2nd Name          Job  Age  Celery
ID
1        Anna    Kowalska      Manager   35    8000
2         Jan       Nowak  Programista   28    4500
3   Katarzyna  Wiśniewska   Konsultant   40    6000
4      Tomasz   Kaczmarek  Programista   30    5500
5      Michał   Zieliński      Manager   45    7000

In [11]:
df2[df2["Celery"] > 5000] # zad 4 a

         Name    2nd Name          Job  Age  Celery
ID
1        Anna    Kowalska      Manager   35    8000
3   Katarzyna  Wiśniewska   Konsultant   40    6000
4      Tomasz   Kaczmarek  Programista   30    5500
5      Michał   Zieliński      Manager   45    7000

In [12]:
df2.sort_values(by="Age") #zad4 b

         Name    2nd Name          Job  Age  Celery
ID
2         Jan       Nowak  Programista   28    4500
4      Tomasz   Kaczmarek  Programista   30    5500
1        Anna    Kowalska      Manager   35    8000
3   Katarzyna  Wiśniewska   Konsultant   40    6000
5      Michał   Zieliński      Manager   45    7000

In [13]:
df2[["Job","Celery"]].groupby("Job").mean()

             Celery
Job
Konsultant   6000.0
Manager      7500.0
Programista  5000.0

In [27]:
#Nie dokońca rozumiem o co chodzi w zad 4 D. Chyba chodzi o stworzenie nowego DataFrame z niektórymi pracownikami którzy dostali awans i podmienić ich miejsca w df2 
awanse = {"ID":[3,4],
         "Job":["Programista", "Manager"]}
awanse=pd.DataFrame(awanse).set_index("ID")

In [28]:
df2.update(awanse)

In [29]:
df2 #4 D

         Name    2nd Name          Job  Age  Celery
ID
1        Anna    Kowalska      Manager   35    8000
2         Jan       Nowak  Programista   28    4500
3   Katarzyna  Wiśniewska  Programista   40    6000
4      Tomasz   Kaczmarek      Manager   30    5500
5      Michał   Zieliński      Manager   45    7000

In [35]:
df2.to_csv("Output.csv") #4E

In [36]:
pd.read_csv("Output.csv")

   ID       Name    2nd Name          Job  Age  Celery
0   1       Anna    Kowalska      Manager   35    8000
1   2        Jan       Nowak  Programista   28    4500
2   3  Katarzyna  Wiśniewska  Programista   40    6000
3   4     Tomasz   Kaczmarek      Manager   30    5500
4   5     Michał   Zieliński      Manager   45    7000

In [37]:
df3={
"Nr_albumu": [1, 2, 3, 4, 5],
"Imię": ["Anna", "Jan", "Katarzyna", "Tomasz", "Michał"],
"Nazwisko": ["Kowalska", "Nowak", "Wiśniewska", "Kaczmarek", "Zieliński"],
"Ocena": [4.5, 3.0, 5.0, 4.0, 2.5],
"Wiek": [22, 21, 24, 23, 25]
}

In [41]:
df3 = pd.DataFrame(df3).set_index("Nr_albumu")

In [44]:
df3[df3["Ocena"]>4]

                Imię    Nazwisko  Ocena  Wiek
Nr_albumu
1               Anna    Kowalska    4.5    22
3          Katarzyna  Wiśniewska    5.0    24

In [45]:
df3.sort_values("Wiek")

                Imię    Nazwisko  Ocena  Wiek
Nr_albumu
2                Jan       Nowak    3.0    21
1               Anna    Kowalska    4.5    22
4             Tomasz   Kaczmarek    4.0    23
3          Katarzyna  Wiśniewska    5.0    24
5             Michał   Zieliński    2.5    25

In [48]:
df3.groupby("Ocena")["Wiek"].mean()

Ocena
2.5    25.0
3.0    21.0
4.0    23.0
4.5    22.0
5.0    24.0
Name: Wiek, dtype: float64

In [58]:
poprawa = {"Nr_albumu":[5,2],
          "Ocena":[3,3.5]}

In [59]:
poprawa = pd.DataFrame(poprawa).set_index("Nr_albumu")
poprawa

           Ocena
Nr_albumu
5            3.0
2            3.5

In [60]:
df3.update(poprawa)

In [61]:
df3

                Imię    Nazwisko  Ocena  Wiek
Nr_albumu
1               Anna    Kowalska    4.5    22
2                Jan       Nowak    3.5    21
3          Katarzyna  Wiśniewska    5.0    24
4             Tomasz   Kaczmarek    4.0    23
5             Michał   Zieliński    3.0    25

In [63]:
df3.to_csv("Zad5.csv")

In [64]:
pd.read_csv("Zad5.csv")

   Nr_albumu       Imię    Nazwisko  Ocena  Wiek
0          1       Anna    Kowalska    4.5    22
1          2        Jan       Nowak    3.5    21
2          3  Katarzyna  Wiśniewska    5.0    24
3          4     Tomasz   Kaczmarek    4.0    23
4          5     Michał   Zieliński    3.0    25

In [66]:
df3["Ocena"].unique()

array([4.5, 3.5, 5. , 4. , 3. ])

In [69]:
sum(df3["Ocena"]==5)

1